/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_caffeineswitch_lib_getcmn_Net */

#ifndef _Included_net_caffeineswitch_lib_getcmn_Net
#define _Included_net_caffeineswitch_lib_getcmn_Net
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_caffeineswitch_lib_getcmn_Net
 * Method:    initNetIntf
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_caffeineswitch_lib_getcmn_Net_initNetIntf
  (JNIEnv *, jobject);

/*
 * Class:     net_caffeineswitch_lib_getcmn_Net
 * Method:    getNetIntfNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_caffeineswitch_lib_getcmn_Net_getNetIntfNum
  (JNIEnv *, jobject);

/*
 * Class:     net_caffeineswitch_lib_getcmn_Net
 * Method:    getNetIntfDesc
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_caffeineswitch_lib_getcmn_Net_getNetIntfDesc
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_caffeineswitch_lib_getcmn_Net
 * Method:    getNetIntfInOctet
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_caffeineswitch_lib_getcmn_Net_getNetIntfInOctet
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_caffeineswitch_lib_getcmn_Net
 * Method:    getNetIntfOutOctet
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_caffeineswitch_lib_getcmn_Net_getNetIntfOutOctet
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
