/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_caffeineswitch_lib_getcmn_Mem */

#ifndef _Included_net_caffeineswitch_lib_getcmn_Mem
#define _Included_net_caffeineswitch_lib_getcmn_Mem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_caffeineswitch_lib_getcmn_Mem
 * Method:    getTotalMem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_caffeineswitch_lib_getcmn_Mem_getTotalMem
  (JNIEnv *, jobject);

/*
 * Class:     net_caffeineswitch_lib_getcmn_Mem
 * Method:    getFreeMem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_caffeineswitch_lib_getcmn_Mem_getFreeMem
  (JNIEnv *, jobject);

/*
 * Class:     net_caffeineswitch_lib_getcmn_Mem
 * Method:    getUsedMem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_caffeineswitch_lib_getcmn_Mem_getUsedMem
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
