/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class net_caffeineswitch_lib_getcmn_CPU */

#ifndef _Included_net_caffeineswitch_lib_getcmn_CPU
#define _Included_net_caffeineswitch_lib_getcmn_CPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_caffeineswitch_lib_getcmn_CPU
 * Method:    getCPUUsage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_net_caffeineswitch_lib_getcmn_CPU_getCPUUsage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
